import pyautogui
from pynput import keyboard
import time

def human_click(x, y, wait=0.1):
    pyautogui.moveTo(x, y)
    pyautogui.mouseDown()
    time.sleep(wait)
    pyautogui.mouseUp()

def start_automation():
    print("Automation started...")
    while True:
        time.sleep(6)
        human_click(89.5, 894)
        time.sleep(2)
        human_click(89.5, 894)
        time.sleep(2)
        human_click(89.5, 894)
        time.sleep(2)
        human_click(1075.5, 526.0)
        time.sleep(1)
        human_click(1406.0, 184.0)
        time.sleep(1)
        pyautogui.scroll(-50)
        time.sleep(1) 
        human_click(1405.0, 804.0, wait=0.2)
        time.sleep(1)
        human_click(687.5, 388.5)
        time.sleep(1)
        human_click(755.5, 824.0)
        time.sleep(4.5)
        pyautogui.click(1046.0, 292.5)
        time.sleep(0.5)
        pyautogui.press('e')
        time.sleep(0.5)
        human_click(1046.0, 292.5)
        time.sleep(0.5)
        pyautogui.press('.')
        pyautogui.press('.')
        pyautogui.press(',')
        pyautogui.press('tab')
        pyautogui.press('tab')
        pyautogui.press('tab')
        time.sleep(0.5)
        human_click(677.0, 233.0)
        time.sleep(0.5)
        pyautogui.press('q')
        time.sleep(0.5)
        human_click(677.0, 233.0)
        pyautogui.press(',')
        pyautogui.press(',')
        pyautogui.press('.')
        pyautogui.press('.')
        pyautogui.press('.')
        pyautogui.press('space')
        pyautogui.press('space')
        pyautogui.press('space')
        time.sleep(100)
        human_click(547.0, 307.5) #dm2
        time.sleep(0.5)
        pyautogui.press('q')
        time.sleep(0.5)
        human_click(547.0, 307.5) #dm2
        pyautogui.press(',')
        pyautogui.press(',')
        pyautogui.press('.')
        pyautogui.press('.')
        pyautogui.press('.')
        time.sleep(1.5)
        human_click(522.5, 392.0) #dm3
        time.sleep(1)
        pyautogui.press('q')
        time.sleep(1)
        human_click(522.5, 392.0) #dm3
        pyautogui.press(',')
        pyautogui.press(',')
        pyautogui.press('.')
        pyautogui.press('.')
        pyautogui.press('.')
        time.sleep(1)
        human_click(772.0, 299.5) #dm5
        time.sleep(1)
        pyautogui.press('q')
        time.sleep(1)
        human_click(772.0, 299.5) #dm5
        pyautogui.press(',')
        pyautogui.press(',')
        pyautogui.press('.')
        pyautogui.press('.')
        pyautogui.press('.')
        time.sleep(60)
        human_click(1020.0, 433.0) #sn
        time.sleep(1)
        pyautogui.press('e')
        time.sleep(1)
        human_click(1020.0, 433.0)
        time.sleep(1)
        pyautogui.press('.')
        pyautogui.press('.')
        pyautogui.press(',')
        pyautogui.press('tab')
        pyautogui.press('tab')
        pyautogui.press('tab')
        time.sleep(2.5)
        human_click(920.5, 632.0) #sn
        time.sleep(1)
        pyautogui.press('e')
        time.sleep(1)
        human_click(920.5, 632.0)
        time.sleep(1)
        pyautogui.press('.')
        pyautogui.press('.')
        pyautogui.press(',')
        pyautogui.press('tab')
        pyautogui.press('tab')
        pyautogui.press('tab')
        time.sleep(20)
        human_click(813.0, 296.5) #dm6
        pyautogui.press(',')
        pyautogui.press(',')
        pyautogui.press('.')
        pyautogui.press('.')
        pyautogui.press('.')
        time.sleep(10)
        human_click(551.0, 154.0) #dm7
        time.sleep(1)
        pyautogui.press('q')
        time.sleep(3.5)
        human_click(551.0, 154.0) #dm7
        pyautogui.press(',')
        pyautogui.press(',')
        pyautogui.press('.')
        pyautogui.press('.')
        pyautogui.press('.')
        time.sleep(1)
        human_click(799.0, 171.0) #dm8
        time.sleep(1)
        pyautogui.press('q')
        time.sleep(20)
        human_click(799.0, 171.0) #dm8
        pyautogui.press(',')
        pyautogui.press(',')
        pyautogui.press('.')
        pyautogui.press('.')
        pyautogui.press('.')
        time.sleep(40)
        # ... previous code (dm8) above ...

        # dm9
        human_click(443.0, 632.5) 
        time.sleep(0.5)
        pyautogui.press('q')
        time.sleep(0.5)
        human_click(443.0, 632.5)
        pyautogui.press(',')
        pyautogui.press(',')
        pyautogui.press('.')
        pyautogui.press('.')
        pyautogui.press('.')
        time.sleep(1)

        # dm10
        human_click(677.0, 667.5)
        time.sleep(0.5)
        pyautogui.press('q')
        time.sleep(0.5)
        human_click(677.0, 667.5)
        pyautogui.press(',')
        pyautogui.press(',')
        pyautogui.press('.')
        pyautogui.press('.')
        pyautogui.press('.')
        time.sleep(10)

        # dm11
        human_click(594.0, 507.5)
        time.sleep(0.5)
        pyautogui.press('q')
        time.sleep(0.5)
        human_click(594.0, 507.5)
        pyautogui.press(',')
        pyautogui.press(',')
        pyautogui.press('.')
        pyautogui.press('.')
        pyautogui.press('.')
        time.sleep(10)

        # dm12
        human_click(666.0, 544.0)
        time.sleep(0.5)
        pyautogui.press('q')
        time.sleep(0.5)
        human_click(666.0, 544.0)
        pyautogui.press(',')
        pyautogui.press(',')
        pyautogui.press('.')
        pyautogui.press('.')
        pyautogui.press('.')
        time.sleep(1)

        # dm13
        human_click(320.0, 428.5)
        time.sleep(0.5)
        pyautogui.press('q')
        time.sleep(0.5)
        human_click(320.0, 428.5)
        pyautogui.press(',')
        pyautogui.press(',')
        pyautogui.press('.')
        pyautogui.press('.')
        pyautogui.press('.')
        time.sleep(1)

        # dm14
        human_click(1081.5, 585.5)
        time.sleep(0.5)
        pyautogui.press('q')
        time.sleep(0.5)
        human_click(1081.5, 585.5)
        pyautogui.press(',')
        pyautogui.press(',')
        pyautogui.press('.')
        pyautogui.press('.')
        pyautogui.press('.')
        time.sleep(1)
        human_click(900.0, 816.0)
        time.sleep(4)
        human_click(900.0, 816.0)

        # dm15
        human_click(836.0, 765.0)
        time.sleep(0.5)
        pyautogui.press('q')
        time.sleep(0.5)
        human_click(836.0, 765.0)
        pyautogui.press(',')
        pyautogui.press(',')
        pyautogui.press('.')
        pyautogui.press('.')
        pyautogui.press('.')
        time.sleep(5)
        
        human_click(900.0, 800.0)
        time.sleep(4)
        human_click(900.0, 800.0)
        
        # Sniper 1 
        human_click(761.5, 540.0)
        time.sleep(0.5)
        pyautogui.press('e') # Sniper Hotkey
        time.sleep(0.5)
        human_click(761.5, 540.0)
        time.sleep(1)
        pyautogui.press('.')
        pyautogui.press('.')
        pyautogui.press(',')
        pyautogui.press(',')
        pyautogui.press('.')
        pyautogui.press('tab')
        pyautogui.press('tab')
        pyautogui.press('tab')
        time.sleep(2)
        human_click(900.0, 816.0)
        time.sleep(2)
        human_click(900.0, 816.0)


        human_click(761.5, 485.0)
        time.sleep(0.5)
        pyautogui.press('e')
        time.sleep(0.5)
        human_click(761.5, 485.0)
        time.sleep(1)
        pyautogui.press('.')
        pyautogui.press('.')
        pyautogui.press(',')
        pyautogui.press(',')
        pyautogui.press('tab')
        pyautogui.press('tab')
        pyautogui.press('tab')
        time.sleep(2)
        human_click(900.0, 816.0)
        time.sleep(2)
        human_click(900.0, 816.0)

        # Sniper 3 
        human_click(761.5, 430.0)
        time.sleep(0.5)
        pyautogui.press('e')
        time.sleep(0.5)
        human_click(761.5, 430.0)
        time.sleep(1)
        pyautogui.press('.')
        pyautogui.press('.')
        pyautogui.press(',')
        pyautogui.press(',')
        pyautogui.press('tab')
        pyautogui.press('tab')
        pyautogui.press('tab')
        time.sleep(1)
        human_click(900.0, 816.0)
        time.sleep(2)
        human_click(900.0, 816.0)

        # Sniper 4 
        human_click(761.5, 375.0)
        time.sleep(0.5)
        pyautogui.press('e')
        time.sleep(0.5)
        human_click(761.5, 375.0)
        time.sleep(1)
        pyautogui.press('.')
        pyautogui.press('.')
        pyautogui.press(',')
        pyautogui.press(',')
        pyautogui.press('tab')
        pyautogui.press('tab')
        pyautogui.press('tab')
        time.sleep(8)
        human_click(900.0, 816.0)
        time.sleep(2)
        human_click(900.0, 816.0)
        human_click(1020.0, 433.0) #snq
        time.sleep(1)
        pyautogui.press(',')
        pyautogui.press('.')
        time.sleep(5)
        human_click(920.5, 632.0) #sn
        time.sleep(1)
        pyautogui.press(',')
        pyautogui.press('.')
        time.sleep(8)
        pyautogui.click(1046.0, 292.5)
        time.sleep(0.5)
        pyautogui.press(',')
        pyautogui.press('.')
        human_click(900.0, 816.0)
        time.sleep(4)
        human_click(900.0, 816.0)
        time.sleep(80)
        
        human_click(755.0, 827.0)
        
        

        print("Cycle done.")


def on_press(key):
    try:
        if hasattr(key, 'char') and key.char == 'd':
            start_automation()
        if key == keyboard.Key.esc:
            return False
    except AttributeError:
        pass

with keyboard.Listener(on_press=on_press) as listener:
    listener.join()
